name: Run Spring Batch
on:
  workflow_dispatch: { }
  # schedule:
  # 23:50 JST
  # - cron: '50 14 * * *'
jobs:
  run-batch:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
    - name: Import Secrets
      id: import-secrets
      uses: hashicorp/vault-action@v3.3.0
      with:
        exportToken: true
        exportEnv: true
        method: jwt
        url: ${{ secrets.VAULT_ADDR }}
        role: cicd
        secrets: |
          kv/data/cicd/spring_batch_metadata SPRING_DATASOURCE_URL;
          kv/data/cicd/spring_batch_metadata SPRING_DATASOURCE_USERNAME;
          kv/data/cicd/spring_batch_metadata SPRING_DATASOURCE_PASSWORD;
    - name: Run the docker image
      run: |
        export TZ=Asia/Tokyo
        days_to_subtract=$(( $(date +%u) - 1 ))
        monday_date=$(date -d "$(date +%Y-%m-%d) -$days_to_subtract days" +%Y-%m-%d)
        today=$(date +%Y-%m-%d)
        cat <<EOF > envfile
        MANAGEMENT_OPENTELEMETRY_RESOURCEATTRIBUTES_GITHUB_REPOSITORY=${GITHUB_REPOSITORY}
        MANAGEMENT_OPENTELEMETRY_RESOURCEATTRIBUTES_GITHUB_SHA=${GITHUB_SHA}
        MANAGEMENT_OPENTELEMETRY_RESOURCEATTRIBUTES_GITHUB_RUN_NUMBER=${GITHUB_RUN_NUMBER}
        MANAGEMENT_OTLP_LOGGING_ENDPOINT=${{ secrets.LOGNROLL_APIURL }}/v1/logs
        MANAGEMENT_OTLP_LOGGING_HEADERS_AUTHORIZATION="Bearer ${{ secrets.LOGNROLL_ACCESSTOKEN }}"
        GITHUB_ACCESSTOKEN=${{ secrets.GH_ACCESS_TOKEN }}
        LOGNROLL_APIURL=${{ secrets.LOGNROLL_APIURL }}
        LOGNROLL_ACCESSTOKEN=${{ secrets.LOGNROLL_ACCESSTOKEN }}
        ENTRY_APIURL=${{ secrets.ENTRY_APIURL }}
        SPRING_DATASOURCE_URL=${SPRING_DATASOURCE_URL}
        SPRING_DATASOURCE_USERNAME=${SPRING_DATASOURCE_USERNAME}
        SPRING_DATASOURCE_PASSWORD=${SPRING_DATASOURCE_PASSWORD}
        JAVA_TOOL_OPTIONS=-Duser.timezone=Asia/Tokyo -Duser.country=JP -Duser.language=ja -Dfile.encoding=UTF-8
        EOF
        docker run --rm \
          -e BPL_JAVA_NMT_ENABLED=false \
          -e BPL_JVM_THREAD_COUNT=10 \
          --env-file envfile \
          --pull always \
          ghcr.io/${{ github.repository }}:jvm \
          --spring.datasource.driver-class-name=org.postgresql.Driver \
          reportStartDate=$monday_date,java.time.LocalDate \
          runDate=$today,java.time.LocalDate
